site_name: Custom Shoppingmall Service Docs
nav:
  - Project Information: projectInfo.md
  - Getting started: start.md 
  - REST API Reference: api.md
  - Architecture: architecture.md
  - Erd: erd.md
